### ISSUE TITLE
support configurable subscriptions endpoint

### ISSUE THREAD

**Issue by gaurav107** [prisma/prisma-binding#1]
Instead of hardcoding `wss://subscriptions.graph.cool/v1/${serviceId}` in GraphcoolLink, it should be passed as a param in the root Graphcool ctor which internally passes it to GraphcoolLink ctor. This'll help in testing subscriptions locally using docker

**Comment by maticzav** [comment]
I believe this issue is no longer active. Feel free to reopen if you think differently  🙂
