### ISSUE TITLE
dependency issues when running yarn and using version 1.5.10

### ISSUE THREAD

**Issue by RobinsonKameron** [prisma/prisma-binding#110]
Has anyone else gotten this issue
```[native code]
json@[native code]
promiseReactionJob@[native code]
```
when running
```yarn```

since I upgraded
``` prisma-binding```
to
```1.5.10```
I've gotten that output unless I
```rm -rf yarn.lock```
and run
```npm install```

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its context. 🙂
