### ISSUE TITLE
Prisma breaking Prisma Subscription for any created/updated Entity

### ISSUE THREAD

**Issue by nsignes** [prisma/prisma-binding#131]
Hi,
I encounter a weird behavior where I can reliably break Prisma's subscription by using Prisma Binding to create or update an entity.

As long as I stay into Prisma API, I can create, update and delete an entity, with Prisma subscription firing up every time.

But if I use Prisma Bindings in a GraphQL-Yoga Backend, any entity created or updated by the backend's mutation will no longer trigger subscriptions at all.

Combinations tried :
- Entity created in Prisma : Subscription worked
- Entity created in Prisma, updated in Prisma: Prisma API Subscription worked
- Entity created in Prisma, updated in Backend: Backend Subscription didn't work
- Entity created in Prisma, updated in Prisma, updated in Backend, then updated in Prisma:  Prisma Subscription worked the first time, then Backend Subscription didn't work; then Prisma Subscription didn't work the second time.
- Entity created in Backend:  Backend Subscription worked
- Entity created in Backend, then updated in Prisma: Prisma Subscription didn't work.

All updates and creations were made with the same arguments, with and without the nested mutations.

Thanks,

**Comment by marktani** [comment]
Hey @nsignes, thanks a lot for bringing this up, and for the detailed descriptions.

Can you prepare a repository that showcases the steps necessary to reproduce this? Please include the necessary mutations and subscriptions (and to which endpoint) as well.
 
This will make it easier to pin down the component that is responsible for this behaviour.

Thanks a lot :raised_hands:

**Comment by frankdugan3** [comment]
@nsignes Are you using fragments? I experienced this happening when I used fragments to share the returned node fields.

**Comment by divyenduz** [comment]
If you are using fragments then it is a known bug - https://github.com/prismagraphql/prisma/issues/2026

**Comment by nsignes** [comment]
Hi everyone, thanks for taking the time to reply !

 I wasn't using any fragments. The same subscription simply stopped firing upon updating the entity with bindings.
@marktani : Sorry, didn't see your message :/

 I'll try again to reproduce the issue with the more recent version of Prisma since there have been 3 major versions of Prisma a one major version of Bindings since I tried that.

**Comment by chewy94** [comment]
@nsignes Any luck?

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
