### ISSUE TITLE
Better information for invalid queries

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#16]
<img width="381" alt="bildschirmfoto 2017-12-19 um 20 07 08" src="https://user-images.githubusercontent.com/1780597/34177637-84ec4238-e504-11e7-92f6-2975bbf603e7.png">

this currently returns `null`, instead of a helpful error message.

The error is that the code should say `id: userId` instead of `id: { userId }`.

**Comment by schickling** [comment]
Pending: https://github.com/apollographql/graphql-tools/issues/550

**Comment by kbrandwijk** [comment]
Also, would it help you that the static bindings pick this up at design-time, and you will get a type error?

**Comment by marktani** [comment]
Yes, that is/would be tremendously helpful!

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/34631969-521257f4-f273-11e7-9afc-4b3423dd987b.png)

**Comment by schickling** [comment]
We should still try to find a way to provide better run-time validation for dynamic bindings.

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current `prisma-binding`. The new `graphql-binding` code generator also features a very robust interface system which probably fixes the problem described here.

Feel free to reopen the issue if you believe we should further discuss it. 🙂
