### ISSUE TITLE
Importing into a Typescript project with implicitAny: true causes compile failure

### ISSUE THREAD

**Issue by zachlysobey** [prisma/prisma-binding#166]
When importing this project from my own typescript project, I'm getting `[...]  implicitly has an 'any' type` errors when I try to compile.

The errors seem to originate from `graphql-binding` (*so maybe that's where I should be inquiring?*). But when I ran a similar experiment with that library, and it compiles with no issue.

Any help/insight would be greatly appreciated :)

### `package.json`

```js
{
  "scripts": {
    "build": "tsc"
  },
  "devDependencies": {
    "@types/graphql": "^0.13.1",
    "typescript": "^2.8.1"
  },
  "dependencies": {
    "graphql": "^0.13.0",
    "prisma-binding": "^1.5.19"
  }
}
```

### `tsconfig.json`

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "noImplicitAny": true,
    "lib":["esnext"]
  }
}
```

### `index.ts`

```js
import { Prisma } from 'prisma-binding'
```

### *build output*

$ npm run build

> @ build C:\Users\zachl\workspace\prisma-binding-test
> tsc

```sh
node_modules/graphql-binding/dist/proxy.d.ts(9,32): error TS7006: Parameter 'schema' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(9,40): error TS7006: Parameter 'fragmentReplacements' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(9,62): error TS7006: Parameter 'operation' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(9,73): error TS7006: Parameter 'before' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(17,32): error TS7006: Parameter 'schema' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(17,40): error TS7006: Parameter 'fragmentReplacements' implicitly has an 'any' type.
node_modules/graphql-binding/dist/proxy.d.ts(17,62): error TS7006: Parameter 'before' implicitly has an 'any' type.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by zachlysobey** [comment]
I put that all into a repo in case someone wants to pull it down and take a look
https://github.com/zachlysobey/prisma-binding-test

**Comment by marktani** [comment]
Thinks for bringing this up, @zachlysobey!

Where possible, the types should be stated explicitely. If nothing else, they should say `any`.

That's a great first issue for anyone looking to contribute 🙂

**Comment by medelman17** [comment]
Upgrading to the current version of `prisma-binding` resolves the above issue. However, doing so introduces an additional issue, wherein using `yarn` (v1.6) as package manager pulls the incorrect version of `graphql-tools`, again breaking typescript support. 

> Note: for reasons currently unknown, using `npm` instead of `yarn` resolves the new issue. 

TypeScript support in `prisma-binding` relies on a `TypescriptGenerator` provided by `graphql-binding.` This generator imports and exports a Transform interface that is included in `graphql-tools@^3.0.1`, but not in earlier 2.x versions. Thus, when `yarn` installs the incorrect version, typescript support breaks.  _See also_ https://github.com/apollographql/graphql-tools/issues/787. 

The anomalous yarn behavior appears to occur, at least in part, as a result of `graphql-yoga` listing a 2.X version of `graphql-tools` in its dependencies as changing `yoga`'s dependency to the latest version resolves the issue.

**Comment by onpaws** [comment]
I checked in on the graphql-yoga [PR](https://github.com/prismagraphql/graphql-yoga/pull/331) and for the sake of graphql-yoga and prisma-binding users out there, hope the maintainers can give accept it soon. 

As of today been open for 10 days...

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
