### ISSUE TITLE
Getting TS error on advanced boilerplate strict:true in tsconfig.json 

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#175]
originally reported by @jhalborg here: https://github.com/graphql-boilerplates/typescript-graphql-server/issues/257

---

I get the following TS error

```
src/index.ts(5,34): error TS2345: Argument of type '{ typeDefs: string; resolvers: typeof "/.../src/...' is not assignable to parameter of type 'Props'.
  Types of property 'resolvers' are incompatible.
    Type 'typeof "/.../src/resolvers/index"' is not assignable to type 'IResolvers | undefined'.
      Type 'typeof "/.../src/resolvers/index"' is not assignable to type 'IResolvers'.
        Property 'default' is incompatible with index signature.
          Type '{ Query: { feed(parent: any, args: any, ctx: Context, info: any): Promise<Post[]>; drafts(parent:...' is not assignable to type 'GraphQLScalarType | (() => any) | IResolverObject'.
            Type '{ Query: { feed(parent: any, args: any, ctx: Context, info: any): Promise<Post[]>; drafts(parent:...' is not assignable to type 'IResolverObject'.
              Property 'Query' is incompatible with index signature.
                Type '{ feed(parent: any, args: any, ctx: Context, info: any): Promise<Post[]>; drafts(parent: any, arg...' is not assignable to type 'GraphQLFieldResolver<any, any, { [argName: string]: any; }> | IResolverOptions'.
                  Type '{ feed(parent: any, args: any, ctx: Context, info: any): Promise<Post[]>; drafts(parent: any, arg...' has no properties in common with type 'IResolverOptions'.
```

This was before the (very) recent update to the `generated/prisma.ts` in the boilerplate. I did try to copy+paste the changed `prisma.ts` from this repo into my own project, but the error persisted. 

I only changed:
* .gitignore
* created `tslint.json`, `settings.json`
* edited `package.json` and `tsconfig.json`

__________________________
**EDIT**: I found the culprit. Adding `strict:true` to `tsconfig.json` displays the error.

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
