### ISSUE TITLE
Prisma-binding produces incorrect types for nullable update mutations

### ISSUE THREAD

**Issue by FrankSandqvist** [prisma/prisma-binding#188]
For a type with a nullable field, I should be able to send a mutation to update any of the nullable fields to null.

E.g.
```
ctx.db.mutation.updateCompany({
    where: { slug: "myCompany" },
    data: { vatNumber: null }
}, info);
```

However this yields a typescript error “Type ‘null’ is not assignable to type ‘string | undefined’.” This is because Prisma-binding produces incorrect types for the update input:

```
export interface CompanyUpdateInput {
  slug?: String
  name?: String
  vatNumber?: String
  businessId?: String
}
```

The nullable fields (vatNumber & businessId) should have the union type String | null, so I can null them if I wish.

https://www.prisma.io/forum/t/prisma-binding-produces-incorrect-types-for-nullable-update-mutations/3771

Best,
Frank

**Comment by FrankSandqvist** [comment]
Or as nilan suggested String | null | undefined. 

Supposed both 

field?: Type | null

and 

field: Type | null | undefined

could work?

**Comment by mattferrin** [comment]
I had to do:

```ts
    const data = { vatNumber: null };

    ctx.db.mutation.updateCompany(
      {
        where: { slug: "myCompany" },
        data
      },
      info
    );
```

**Comment by agonbina** [comment]
You can also use `null!` to turn the null into a `never` type, which is accepted for any type. Obviously this does not solve the actual problem, which is that the autogenerated type is plain wrong.

**Comment by nemcek** [comment]
Any update on fixing generated types?

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂

**Comment by nemcek** [comment]
Hey @maticzav I don't see how this is out of sync.
Using prisma-binding@2.2.8 with datamodel as
```graphql
type Post {
  id: ID! @unique
  title: String!
  body: String
}
```
The generated types are:
```graphql
// ...
export interface Post extends Node {
  id: ID_Output
  title: String
  body?: String
}
// ...
export interface PostCreateInput {
  title: String
  body?: String
}
// ...
export interface PostUpdateInput {
  title?: String
  body?: String
}
```
No `nullable` types anywhere.
I think this should be resolved in `graphql-binding` and not `prisma-binding` as people can use `graphql-binding` to generate types for their own bindings.
