### ISSUE TITLE
Typescript definition of Mutations and Queries does not conform to reality

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#199]
@tomitrescak commented on [Tue Jul 10 2018](https://github.com/prismagraphql/prisma/issues/2751)

Is there any particular reason why the Query and Mutation functions are generated with 3 parameters only? For example:

```ts
export interface Query {
    authenticate: <T = String>(args: { username?: String, password?: String }, info?: GraphQLResolveInfo | string, options?: Options) => Promise<T> ,
}
```

In reality, these resolver functions have four parameters. So correct way would be:

```ts
export interface Query {
    authenticate: <T = String>(parent: any, args: { username?: String, password?: String }, context: Prisma, info?: GraphQLResolveInfo | string) => Promise<T> {
}
```

I tried searching for the solution but cannot find any. Thanks

**Comment by marktani** [comment]
@tomitrescak can you provide some more context? Where are these function signatures extracted from?

**Comment by tomitrescak** [comment]
Hi, it is the standard header of Apollo server resolver. For example:

```ts
export const query: Query = {
  notifications(_parent, { start, end }, ctx, info) {
    return ctx.db.query.notifications(
      { where: { owner: { id: getUserId(ctx) } }, skip: start, last: end },
      info
    );
  }
};
```

Until this is resolved I did a little Typescript magic to remap the function parameters ;)

```ts
import { Mutation as PrismaMutation, Query as PrismaQuery } from '../generated/api';
import { Prisma, User } from '../generated/prisma';

type FirstArgument<T> = T extends (arg1: infer U, ...args: any[]) => any ? U : any;

// remap parameters to match apollo query and mutation handler
type Remapped<T> = {
  [P in keyof T]: (parent: any, args: FirstArgument<T[P]>, ctx: Context, info: any) => any
};

export type Query = Partial<Remapped<PrismaQuery>>;
export type Mutation = Partial<Remapped<PrismaMutation>>;
```

Since this solution provides enough flexibility to remap to any header as necessary we can close this issue.

**Comment by tomitrescak** [comment]
I'm not sure if it is obvious from the xample above, but doing so you obtain absolute type safety on all resolver and mutations, including the mutation and query parameters ;))

I can only say ... I LOVE YOU GUYS!!! 💘 

The only thing I'm not sure of is type of parent and info, but that is almost never used.

**Comment by medelman17** [comment]
This may actually be a `graphql-binding` issue as that is where the TS generator lives.

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
