### ISSUE TITLE
Delegating to field with different type

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-binding#2]
I have the following data model:

```graphql
type Post @model {
  id: ID! @isUnique
  title: String!
  author: User! @relation(name: "UserPosts")
  comments: [Comment!]! @relation(name: "CommentsOnPost")
}

type User @model {
  id: ID! @isUnique
  email: String! @isUnique
  password: String!
  name: String!
  posts: [Post!]! @relation(name: "UserPosts")
  comments: [Comment!]! @relation(name: "UserComments")
}

type Comment @model {
  id: ID! @isUnique
  text: String!
  post: Post! @relation(name: "CommentsOnPost")
  writtenBy: User! @relation(name: "UserComments")
}
```

Now, in my `app.graphql` I want specify the following root field:

```graphql
# import Comment from "./database.graphql"

type Query {
  commentsForPost(id: ID!): [Comment!]!
}
```

Now, the straightforward way to implement this would be to delegate to `query.comments` and passed the post's `id` as a filter. However, it feels more "natural" to fetch the specific `Post` including its `comments`, but this doesn't really work with the API. this is what the resolver would look like:

```js
  async commentsForPost(parent, { id }, ctx: Context, info) {
    const selection = `{ comments { id text } }`
    const post = await ctx.db.query.post({id}, selection)
    return post.comments
  }
```

This but the problem is the selection set is not complete. Once a query also asks for the `writtenBy` field of the `comments`, this will break because `selection` doesn't include that info.

**Comment by kbrandwijk** [comment]
I think this would be solved by the fact that info would already contain that field information, so if you pass in `info` instead of `selection` to the `post` method, that _should_ just work.

**Comment by maticzav** [comment]
I believe this issue is no longer in sync with the current `prisma-binding`, however, for the sake of sharing the idea, you could also fetch `comments` in the first place which would prevent this cumbersome situation.

```ts
async commentsForPost(parent, { id }, ctx: Context, info) {
  return ctx.db.query.comments({ post: { id } }, info)
}
```

Feel free to reopen the issue 🙂
