### ISSUE TITLE
Are there plan to upgrade deps?

### ISSUE THREAD

**Issue by joe-re** [prisma/prisma-binding#210]
I want to update subscriptions-transport-ws and it seems like PR already exist by Renovate.
https://github.com/prismagraphql/prisma-binding/pull/165

and many other updating deps PRs are, do you have any plan or policy to merge them?

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
