### ISSUE TITLE
Make difference in usage between TS and JS clear in README

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#212]
TypeScript requires a generated `prisma.ts` file that can be imported like that:

```typescript
import { Prisma } from './generated/prisma'

new Prisma({
      endpoint: process.env.PRISMA_ENDPOINT,
      debug: true,
      secret: process.env.PRISMA_SECRET,
    }),
```

With JavaScript you need to pass in the schema `prisma.graphql` into `typeDefs`:

```javascript
const { Prisma } = require('prisma-binding')

const db = new Prisma({
  typeDefs: 'src/generated/prisma.graphql',
  endpoint: process.env.PRISMA_ENDPOINT,
  debug: true,
  secret: process.env.PRISMA_SECRET,
})
```

**Comment by czystyl** [comment]
@marktani What do you think about adding the **Flow** instruction as well? 

#214 needs to be merged, then I can write docs for Flow 💪

**Comment by czystyl** [comment]
Now, after spending some time with Flow, I can confirm that you should use generated files. 

Check out my comment here https://github.com/prismagraphql/prisma-binding/issues/187#issuecomment-407817428

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
