### ISSUE TITLE
Prisma has wrong constructor options

### ISSUE THREAD

**Issue by niba** [prisma/prisma-binding#224]
Here is how Prisma is defined in generated types
![image](https://user-images.githubusercontent.com/2017454/43686065-c68b8a72-98bf-11e8-8b2e-f6b5632f8fd3.png)

as you can see Typescript type inference translates Prisma type to: `BindingConstructor<Prisma>`

the definition of BindingContructor is the following:
```
export interface BindingConstructor<T> {
  new(options: BasePrismaOptions): T
}
```

so basically Prisma contructor takes `BasePrismaOptions` options which don't have field like `typeDefs` and that leads us to error when constructing GraphQLServer

```
const server = new GraphQLServer({
  typeDefs: 'src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    prisma: new Prisma({
      typeDefs: 'src/generated/prisma.graphql',
      endpoint: "http://localhost:4466",
    }),
  }),
})
```
and the Typescript error: 

> [ts]
> Argument of type '{ typeDefs: string; endpoint: string; }' is not assignable to parameter of type 'BasePrismaOptions'.
>   Object literal may only specify known properties, and 'typeDefs' does not exist in type 'BasePrismaOptions'.

**Comment by ryankauk** [comment]
+1

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
