### ISSUE TITLE
Unify response from delegate and request

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/prisma-binding#23]
The delegates and the `request` method have different response formats. The request has `data.myQuery`, the delegates return the response directly. This makes it harder to interoperate.

Proposal: return the first element from data for `request`.

**Comment by kbrandwijk** [comment]
@schickling Can I get your feedback on this issue, because it affects the way resolvers are implemented.

**Comment by schickling** [comment]
Sorry for the delay @kbrandwijk. So far that was actually intended. `request` is meant as a "ready-to-use" version of `graphql-request` (therefore the name). Can you elaborate more on some concrete problems you see with the current design?

**Comment by kbrandwijk** [comment]
Because it is used in a context of resolvers, where all resolvers (built-in or delegated) return the data itself. That means that if I run into a use case where a binding delegate call is not sufficient, and I just want to specify my own query and call request on the binding, I suddenly get the data in a different format. I personally think it would be best (within the context of bindings) that they are interchangeable.

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its context. 🙂
