### ISSUE TITLE
Cannot create resolver with variable named 'after'

### ISSUE THREAD

**Issue by nathanforce** [prisma/prisma-binding#243]
This sounds like a similar issue to #73.  When my resolver expects a variable named `after` to be used for filtering I am seeing an empty result set returned.  My suspicion is that this variable name is conflicting with the `after` variable Prisma uses for pagination.  For now, I have changed the variable name, but ideally I would be able to use any name I'd like.

```
    "graphql-yoga": "1.16.2",
    "prisma-binding": "2.1.6"
```

```
posts: async (
      parent,
      { author, first, after },
      context: Context,
      info
    ) => {
      return context.db.query.posts(
        {
          where: {
            author: { id: author },
            time: { start_gte: after },
          },
          first,
        },
        info
      );
    },
```

Please let me know if there is any more information I can provide.

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its content. 🙂
