### ISSUE TITLE
Support graphql@14

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-binding#249]
As needed in https://github.com/prisma/prisma/issues/3454

**Comment by vkouk** [comment]
Why i am still facing the same issue ?

**Comment by maticzav** [comment]
@vkouk could you check if you by chance have externally defined `graphql` instance? Also, what's the version of `prisma-binding` that you're using?

**Comment by vkouk** [comment]
These are my dependencies: 

dependencies": {
    "bcryptjs": "^2.4.3",
    "dotenv": "^6.1.0",
    "graphql": "^14.0.2",
    "graphql-cli": "^2.17.0",
    "graphql-yoga": "^1.16.7",
    "jsonwebtoken": "^8.4.0",
    "prisma": "^1.21.1",
    "prisma-binding": "^2.2.8"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.6",
    "@babel/node": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "env-cmd": "^8.0.2",
    "nodemon": "^1.18.7"
  },

And my scripts:

"scripts": {
    "start": "node dist/server.js",
    "dev": "env-cmd src/config/dev.env nodemon src/server.js --ext js,graphql --exec babel-node",
    "deploy:dev": "prisma deploy --env-file src/config/dev.env",
    "deploy:prod": "prisma deploy --env-file src/config/prod.env",
    "get-schema": "graphql get-schema -p prisma",
    "generate-schema": "prisma generate -e src/config/dev.env",
    "heroku-postbuild": "babel src -d dist && cp ./src/schema.graphql ./dist"
  },

**Comment by vkouk** [comment]
https://github.com/prisma/prisma/issues/3454

This is still being an issue to me.

**Comment by maticzav** [comment]
@vkouk `get-schema` still hasn't been updated. We'll probably give it a shot this week. Stay put! 😄

**Comment by vkouk** [comment]
@maticzav oh ok then. i will be waiting for an update. I may also use an env prefix? 
ex.: --env dev.env or prod.env for my prisma url or is not needed?
