### ISSUE TITLE
Need clarification around subscription previous values

### ISSUE THREAD

**Issue by chanlito** [prisma/prisma-binding#266]
<img width="452" alt="screen shot 2018-11-26 at 10 57 22 am" src="https://user-images.githubusercontent.com/15667259/48992424-2ab2fa00-f16a-11e8-9cec-9fc50dfadad4.png">

Is previousValues `id` supposed to have this `StringIdGCValue` before the id now? because in previous version I didn't see this.

Is it a bug?

**Comment by maticzav** [comment]
@do4gr could this be related to core `prisma`?

**Comment by do4gr** [comment]
Sorry for the late reply, that was a bug that was fixed in 1.23.1. 

See https://github.com/prisma/prisma/issues/2847
