### ISSUE TITLE
API to combine multiple query fields into one request

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#4]
> In this case I would prefer to combine the two queries into one and use aliases to get the two results. Or does dataloader automatically combine them?

```js
async realzTopPost(parent, args, ctx: Context, info) {
    const {containing} = args

    const [inTitle, inText] = await Promise.all([
      ctx.db.query.posts({first: 1, filter: {title_contains: containing}}, info).then(x => x.find(x => true)),
      ctx.db.query.posts({first: 1, filter: {text_contains: containing}}, info).then(x => x.find(x => true))])

    return inTitle || inText
  }
```

thanks to @sorenbs for reporting! 😎

**Comment by kbrandwijk** [comment]
As far as I'm concerned, this should be covered by transport level batching, which is way easier than combining and aliasing into a single query.
But if there are valid reasons to batch on a query level, please share.

**Comment by schickling** [comment]
I'm wondering whether we could save the `.then(x => x.find(x => true))` part. Other than that I'm a bit concerned about diverting too much from the original GraphQL query. I'd suggest to collect more use cases first and then re-evaluate the design.

**Comment by bazaglia** [comment]
@kbrandwijk I liked this API. Makes sense to me. @schickling are you thinking of implementing this feature into graphql-binding?

**Comment by bazaglia** [comment]
Is it related with #89? Maybe just using `BatchedHTTPLink` works out of the box.

**Comment by maticzav** [comment]
I believe this issue is no longer in sync with the current `prisma-binding`. You might as well want to check [prisma-cli](https://www.prisma.io/client/client-javascript/) which reflected such ideas in the API.

Feel free to reopen the issue if you believe it hasn't been resolved 🙂
