### ISSUE TITLE
Provide better error message for refused connection

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-binding#43]
@marktani commented on [Wed Dec 20 2017](https://github.com/graphcool/graphcool-server-example/issues/16)

```
Error: request to http://localhost:60000/api/example-airbnb/dev failed, reason: connect ECONNREFUSED
127.0.0.1:60000
    at Object.checkResultAndHandleErrors (/Users/marktani/projects/playground/beta-1.1/graphcool-serv
er-example/node_modules/graphql-tools/src/stitching/errors.ts:84:7)
    at Object.<anonymous> (/Users/marktani/projects/playground/beta-1.1/graphcool-server-example/node
_modules/graphql-tools/src/stitching/delegateToSchema.ts:91:14)
    at step (/Users/marktani/projects/playground/beta-1.1/graphcool-server-example/node_modules/graph
ql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/Users/marktani/projects/playground/beta-1.1/graphcool-server-example/node_module
s/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/Users/marktani/projects/playground/beta-1.1/graphcool-server-example/node_modules/
graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

My `localdatabase_graphcool-database_1` container is on port `60001` and not `60000`. We could return an error like

> Error: request to http://localhost:60000/api/example-airbnb/dev failed, this is probably because  your docker container `localdatabase_graphcool-database_1` is not running on port 60000. Run `docker ps` to find out the port and update `.env` accordingly.

**Comment by crazyyi** [comment]
Yes this is very annoying. It takes me a lot of time to debug.

**Comment by matthewdschulman** [comment]
We are getting this same issue. Any update @marktani ?

**Comment by schickling** [comment]
We'll be looking into it @matthewdschulman! Which version of `prisma-binding` and `prisma` are you using? Do you have a reliable way to reproduce this error?

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its context. 🙂
