### ISSUE TITLE
Leverage graphql-config extension for configuration context

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-binding#6]
```ts
const graphcool = new Graphcool({
  schemaPath: "schemas/database.graphql",
  endpoint: process.env.GRAPHCOOL_ENDPOINT,
  secret: process.env.GRAPHCOOL_SECRET,
})
```

Most information provided in the previous snippet is available in the `.graphqlconfig` file. It would be interesting to see whether this information could be read automatically without the need to specify it.

My current understanding is that the `schemaPath` can be always used and therefore can be left out if a `.graphqlconfig` file is available. The more difficult part is around the endpoint and secret as this information changes from stage to stage. This needs to be further researched.

**Comment by kbrandwijk** [comment]
Would it be possible to extend the functionality of the Graphcool extension for `graphql-config` to retrieve the endpoint and secret as well via `graphql-config`?

**Comment by schickling** [comment]
This is a bit tricky. Here are some scenarios with obvious downsides:

1. **Inject the value for `secret` and `endpoint` at "build time"** (i.e. when the static binding is generated). This however could mean that sensitive information/secrets are committed to version control

2. **Retrieve `secret` and `endpoint` at runtime**: This would require you to also deploy the `graphqlconfig` & `graphcool.yml` file (possibly even the `.env` file) but still wouldn't work since to infer the `endpoint` you'd need access to the `~/.graphcoolrc` file (or Graphcool Cloud).

Maybe you can think of other ways or solutions for these issues?

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current prisma-binding.

Feel free to reopen the issue if you believe we should further discuss it. 🙂
