### ISSUE TITLE
Allow using plain object for GraphQLResolveInfo or some way to automate it

### ISSUE THREAD

**Issue by pie6k** [prisma/prisma-binding#64]
Consider schema where `User` have `boughtProducts` and each `Product` have a list of categories.

Consider you query for the user and want to have informations about all products he/she bought and all categories of those products. 

Writing string 'query' to have all those informations resolved looks ugly and is not type-safe. In case of schema change, also, there is no easy way to know if it introduced some errors.

Consider using objects instead where you define what fields you need by setting them to `true` or nested object:

```
const productsWithDetails = await ctx.db.query.users(query, {
  boughtProducts: {
    price: true,
    categories: {
      name: true,
      id: true
    },
    // or even categories: '*',
  },
  name: true,
  age: true,
})
```

It will lead to a lot of true values, but it could have auto-generated interfaces and be type-safe so in case of schema changes you'd see errors, and also it'd be helpful to have IDE suggestions about such interface instead of writing plain string.

I'm aware such approach would introduce a new format and it might be a terrible idea. I'm just thinking about any easy and type-safe way to define nested data requirements of the queried object.

Also, maybe in case when you need all the fields of some object and their 1,2 level nested children, there is some way to generate such `GraphQLResolveInfo` object instead of writing it by-hand as string?

`ctx.db.query.tasks(queryWhere, someTypeSafeDefinitionOf3LevelsNestedFields);`

**Comment by pie6k** [comment]
I thought about using some object instead of string eg. (considering user has products and products has categories)

```
const productsWithDetails = await ctx.db.query.users(query, {
  boughtProducts: {
    price: true,
    categories: {
      name: true,
      id: true
    }
  },
  name: true,
  age: true,
})
```

It will lead to a lot of `true` values, but it could have auto-generated interfaces so in case of schema changes you'd see errors, and also it'd be helpful to have IDE suggestions about such interface instead of writing plain string.

**Comment by kbrandwijk** [comment]
I like the idea of introducing Type safety for the info object. Basically, all the information should already be available, because type definitions are generated for the entire schema, so it should be possible to use a type safe info object from it, which is basically an object for every root field with all it's scalar fields set to boolean.

**Comment by terion-name** [comment]
For this you can use a package: https://github.com/dupski/json-to-graphql-query

But this approach really don't handle lots of issues.
You still will have problems proxying variables or using fragments. Bindings semantics is very limited. It really should accept a GraphQLResolveInfo-like object (or sort of) that will take query/operation, fragments, variableValues. I need a lot of times to **alter** incoming request. For example to ensure return fields for usage in nested resolvers, or to change some props at query, keeping args and variables in place. Now it is VERY hard to do

**Comment by calummoore** [comment]
It would also be helpful to have an object to merge requested fields from the user, with required fields from the system. For example, when running a `create` mutation, you need the ID field, but the user may not have requested it

```js
async function resolver (parent, { input }, ctx, info) {
  const resp = await ctx.db.mutation.createSite(
      {
        data: {
          name,
        },
      },
      info, // Info is provided by the user
  )
  // ID will only be available if the user requested it
  // but I may want to use the ID
  const id = resp.id
  return resp
}
```

**Comment by terion-name** [comment]
@calummoore yes, this is so common case that I don't understand why there is no method for this. I am going to try making sort of `ensureSelection` helper, but yet had no time for this

**Comment by calummoore** [comment]
That would be helpful, not straight forward though! Basically we just need to merge two sets of fields together (which would be easiest if we could merge objects).

As a workaround for now I am making the initial request with the system fields I require, and then a secondary request for fields the user wants. Not ideal obviously, as that's two round trips to the server.

**Comment by terion-name** [comment]
@calummoore I've came along with such thing:
```js
import {graphQLQueryToJson, jsonToGraphQLQuery} from "../graphql/query";
import {merge, head} from "lodash";
import {GraphQLResolveInfo, parse, print, visit, Kind, Source} from "graphql";

export function copyFieldNodes({fieldNodes, operation}) {
  return print(fieldNodes)
      .map(i => {
        const parsedSource = parse(new Source(`${operation.operation} { ${i} }`));
        return parsedSource.definitions[0].selectionSet.selections[0];
      })
}

export function copyResolverInfo(info: GraphQLResolveInfo, overrides = {}): GraphQLResolveInfo {
  return Object.assign({}, info,
      {
        fieldNodes: copyFieldNodes(info),
        fieldName: info.fieldName,
        ...overrides
      }
  )
}

export function transformResolverInfoSelection(info: GraphQLResolveInfo, actions: {forceSelection?: string, rootFieldOverride?: string}) {
  const {forceSelection, rootFieldOverride} = actions;
  const {fieldName} = info;
  let resultSelection = graphQLQueryToJson(info, true);

  if (forceSelection) {
    const requiredSelection = graphQLQueryToJson(`{ ${fieldName} ${forceSelection} }`, true);
    resultSelection = merge(resultSelection, requiredSelection);
  }

  if (rootFieldOverride) {
    resultSelection = {[rootFieldOverride]: head(Object.values(resultSelection))};
  }

  const parsed = parse(`{ ${jsonToGraphQLQuery(resultSelection)} }`);
  const infoCopy = copyResolverInfo(info);
  infoCopy.fieldNodes[0].selectionSet = parsed.definitions[0].selectionSet.selections[0].selectionSet;
  if (rootFieldOverride) {
    infoCopy.fieldNodes[0].name.value = rootFieldOverride;
  }
  return infoCopy;
}
```

This allows to minimally transform input query (reassign root field, add some selections) to pass down to prisma or other graphql endpoint. Minimal and far from perfect, but something.

But in general query transforms when working graphql-to-graphql are very needed and a library for this should be developed

**Comment by jide** [comment]
@terion-name Where does `import {graphQLQueryToJson, jsonToGraphQLQuery} from "../graphql/query";` come from ? jsonToGraphQLQuery id probably https://www.npmjs.com/package/json-to-graphql-query but I could not find the opposite.

**Comment by terion-name** [comment]
@jide sorry, it's my script, I didn't publish it yet.

```js
import {merge} from "lodash";
import {parse} from "graphql";
import {EnumType, VariableType} from "json-to-graphql-query";

export default function graphQLQueryToJson() {
  let tree;
  let info = arguments[0];
  let keepRoot = arguments[1];
  let fieldNodes = info && (info.fieldASTs || info.fieldNodes);
  // let querySelections = info.operation?.selectionSet?.selections;
  if (fieldNodes) {
    // (info, keepRoot)
    tree = fieldTreeFromAST([...fieldNodes], info.fragments);
    if (!keepRoot) {
      let key = Object.keys(tree)[0];
      tree = tree[key]
    }
  } else if (typeof info === "string") {
    const ast = parse(info);
    tree = fieldTreeFromAST(ast.definitions[0].selectionSet.selections);
    if (!keepRoot) {
      let key = Object.keys(tree)[0];
      tree = tree[key]
    }
  } else {
    // (asts, fragments, fieldTree)
    tree = fieldTreeFromAST(...arguments)
  }
  return tree
}

function fieldTreeFromAST (asts, fragments = {}, init = {}) {
  asts = asts instanceof Array ? asts : [asts];
  return asts.reduce(function (tree, val) {
    // console.log(val);
    let kind = val.kind;
    let name = val.name && val.name.value;
    let fragment;
    if (kind === 'Field') {
      if (val.selectionSet) {
        tree[name] = tree[name] || {};
        fieldTreeFromAST(val.selectionSet.selections, fragments, tree[name]);
        if (val.arguments?.length) {
          tree[name].__args = graphQLArgumentsToJson(val.arguments);
        }
      } else {
        tree[name] = true
      }
    } else if (kind === 'FragmentSpread') {
      fragment = fragments[name];
      fieldTreeFromAST(fragment.selectionSet.selections, fragments, tree)
    } else if (kind === 'InlineFragment') {
      fragment = val;
      fieldTreeFromAST(fragment.selectionSet.selections, fragments, tree)
    } // else ignore
    return tree
  }, init)
}

function graphQLArgumentsToJson(args) {
  let tree = {};
  // this will ensure that it is a graphql ast collecton or an array
  if (!args.forEach) args = [args];
  args.forEach(arg => {
    let tmp = [];
    let fields = arg.value.fields;
    if (!fields) {
      tree[arg.name.value] = arg.value.kind === 'EnumValue' ? new EnumType(arg.value.value) : arg.value.value;
    } else {
      fields.forEach(f => {
        if (f.value.fields) {
          tree[arg.name.value] = merge(tree[arg.name.value] || {}, graphQLArgumentsToJson(f));
        } else {
          let value;
          switch (f.value.kind) {
            case 'Variable':
              value = new VariableType(f.value.name.value);
              break;
            case 'EnumValue':
              value = new EnumType(f.value.value);
              break;
            case 'ListValue':
              value = [];
              f.value.values.forEach(v => value.push(v.value));
              break;
            case 'ObjectValue':
              value = graphQLArgumentsToJson({value: f});
              break;
            default:
              value = f.value.value;
          }
          tmp.push({[f.name.value]: value});
          tree[arg.name.value] = merge(tree[arg.name.value] || {}, ...tmp);
        }
      });
    }
  });
  return tree;
}
```

**Comment by berstend** [comment]
I'm contemplating using the Prisma typescript bindings as ORM in my backend (non-resolver) code and type safety for the info object would be super useful here.

I second @kbrandwijk's notion of re-using the existing type definitions, when I have a little more time I'll try to wrap my head around a solution.

I feel there's huge potential here to ditch TypeORM, etc. altogether when using Prisma. 😄 
Especially the powerful filtering/querying on data from relations is just plain amazing and very cumbersome to do in any of the typical ORMs.

**Comment by marktani** [comment]
Hey @berstend, that sounds super interesting. We are working on improving exactly this use case, and I would love to hear your input on it. Could you ping me in [Slack](https://slack.prisma.io/) (my handle is @nilan)? 🙂

**Comment by maticzav** [comment]
Hey 👋, I believe this issue is no longer in sync with the current version of `prisma-binding`. In need for gaining a better overview of the issues facing the current version, I'll close it.

Feel free to reopen the issue if you believe we should further discuss its context. 🙂
