### ISSUE TITLE
Properties from nested mutations not included in response

### ISSUE THREAD

**Issue by gcangussu** [prisma/prisma-binding#86]
I expect the nested mutations to be included in the response of a call to a `Prisma.mutations.create*` type of function when no `info` argument is presented. For example, consider the following prisma data model:
```graphql
type Company {
  id: ID! @unique
  name: String!
  users: [User!]!
}

type User {
  id: ID! @unique
  name: String!
  email: String! @unique
  password: String!
  company: Company!
}
```

And the following schema:
```graphql
type Mutation {
  signupCompany(companyName: String!, userName: String!, userEmail: String!, password: String!): AuthPayload!
}

type AuthPayload {
  token: String!
  user: User!
}
```

I've defined this resolver using prisma-binding injected on its context as property 'db':
```javascript
export async function signupCompany(parent, args, ctx: Context, info) {
  const { companyName, adminName, adminEmail, password } = args;
  const hashedPassword = await hashPassword(password);
  const user = await ctx.db.mutation.createUser({
    data: {
      name: adminName,
      email: adminEmail,
      password: hashedPassword,
      company: {
        create: { name: companyName },
      },
    },
  });
  return {
    user,
    token: getToken(user),
  };
}
```

But the response of `ctx.db.mutation.createUser(...)` doesn't include the company created in the nested mutation, so if I try to do this:
```graphql
mutation {
  signupCompany(companyName: "JustSocks", adminName: "Gabriel Cangussu", adminEmail: "gabriel@justsocks.com", password: "123password") {
    token
    user {
      id
      name
      email
      company {
        id
        name
      }
    }
  }
}
```

I get the error `Cannot return null for non-nullable field User.company`. I also have this same issue on my login mutation that also returns and `AuthPayload`.

Is there any elegant way of telling `ctx.db.mutation.createUser()` to return the company if the original graphql mutation needs it? Right now I've hard coded a string to the second argument of `createUser()` that includes all properties and sub properties of `User`, but this is not very maintainable as the schema of users and companies can change.

**Comment by kbrandwijk** [comment]
I think just passing through the info argument should work, but I haven't looked at your example in detail.

**Comment by gcangussu** [comment]
@kbrandwijk If I do this I get an error saying I didn't make a subselection for the `createUser` mutation (`Field 'createUser' of type 'User' must have a sub selection`). I think the info argument from my `signupCompany` mutation is incompatible with Prisma's `createUser`.

**Comment by xang555** [comment]
same problem

**Comment by schickling** [comment]
We'll look into this! 👀

**Comment by gcangussu** [comment]
A tool that could allow us to easily take information from the `info` argument of the resolver would be useful  on these cases I think. I thought about something like this:
```javascript
async function myResolver(parent, args, ctx, info) {
  const userInfo = pluck('user', info);
  const user = await ctx.db.mutation.createUser({ ... }, userInfo);
  return { user };
}
```
I tried searching for a tool like `pluck` in my example, but failed to find anything. Then I also started studying the `info` structure to do it myself, but was overwhelmed by its complexity and couldn't put more time into it.

**Comment by schickling** [comment]
That's an interesting idea @gcangussu. Could you open a new issue for this and elaborate a bit further with a few examples?

**Comment by mzygmunt** [comment]
same

**Comment by gcangussu** [comment]
@schickling I've done this on #118. But with only one example, I will try to add other examples later.

**Comment by maticzav** [comment]
Hey 👋,

guessing the mutations wouldn't make much sense because `prisma-binding`, even though it serves as a complement to Prisma, isn't tied directly to it in its core implementation.

As @kbrandwijk mentioned, you should find a way to pass down the `info` parameter. A solution to your problem is implementing `AuthPayload` which receives the correctly modified `info` parameter. Check the code I posted below.

```ts
const AuthPayload = {
  async user({ user: { id }}, args, ctx: Context, info) {
    return ctx.db.query.user({ where: { id }}, info)
  }
}
```

Due to inactivity of this issue, I'll close it but feel free to reopen it if you think we should further discuss its content. 🙂
